# Задание_1

###### Импортируйте библиотеки pandas и numpy. Загрузите "Boston House Prices dataset" из встроенных наборов данных библиотеки sklearn. Создайте датафреймы X и y из этих данных. 

`?` Я может упустил этот момент. Подскажите, откуда берутся эти встроенные данные из библиотеки? Как? Почему они там? Сколько таких данных там? 

In [16]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_boston

In [8]:
boston = load_boston()

In [9]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [10]:
data = boston.data

In [11]:
filename = boston.filename

In [12]:
target  = boston.target

In [13]:
feature_names = boston.feature_names

In [14]:
DESCR = boston.DESCR

In [15]:
data [1]

array([2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
       6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
       1.7800e+01, 3.9690e+02, 9.1400e+00])

In [16]:
feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [17]:
target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [18]:
DESCR

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [19]:
for line in boston.DESCR.split ('\n'):
    print(line)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [20]:
filename

'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\boston_house_prices.csv'

In [21]:
X = pd.DataFrame(data, columns = feature_names)

In [22]:
y = pd.DataFrame(target, columns = ['Price'])

###### Разбейте эти датафреймы на тренировочные (X_train, y_train) и тестовые (X_test, y_test) с помощью функции train_test_split так, чтобы размер тестовой выборки составлял 30% от всех данных, при этом аргумент random_state должен быть равен 42. 

In [23]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
dtypes: float64(13)
memory usage: 51.5 KB


In [3]:
from sklearn.model_selection import train_test_split 

In [25]:
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.3, random_state = 42)

###### Создайте модель линейной регрессии под названием lr с помощью класса LinearRegression из модуля sklearn.linear_model. 

In [4]:
from sklearn.linear_model import LinearRegression

In [27]:
lr = LinearRegression()

###### Обучите модель на тренировочных данных (используйте все признаки) и сделайте предсказание на тестовых. 

In [28]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [29]:
predictions = lr.predict(X_test)

In [30]:
check_test = pd.DataFrame({'y_test': y_test['Price'], 
                         'y_pred': predictions.flatten()},
                         columns=['y_test', 'y_pred'])

In [31]:
predictions[0:5]

array([[28.64896005],
       [36.49501384],
       [15.4111932 ],
       [25.40321303],
       [18.85527988]])

In [32]:
X_test.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
173  0.09178   0.0   4.05   0.0  0.510  6.416  84.1  2.6463   5.0  296.0   
274  0.05644  40.0   6.41   1.0  0.447  6.758  32.9  4.0776   4.0  254.0   
491  0.10574   0.0  27.74   0.0  0.609  5.983  98.8  1.8681   4.0  711.0   
72   0.09164   0.0  10.81   0.0  0.413  6.065   7.8  5.2873   4.0  305.0   
452  5.09017   0.0  18.10   0.0  0.713  6.297  91.8  2.3682  24.0  666.0   

     PTRATIO       B  LSTAT  
173     16.6  395.50   9.04  
274     17.6  396.90   3.53  
491     20.1  390.11  18.07  
72      19.2  390.91   5.52  
452     20.2  385.09  17.27

In [33]:
check_test.head()

y_test     y_pred
173    23.6  28.648960
274    32.4  36.495014
491    13.6  15.411193
72     22.8  25.403213
452    16.1  18.855280

###### Вычислите R2 полученных предказаний с помощью r2_score из модуля sklearn.metrics.

In [5]:
from sklearn.metrics import r2_score 

In [35]:
R2 = r2_score(y_test, predictions)

In [36]:
R2

0.7112260057484878

Данная, построенная модель, работает лучше, чем та, что в учебном материале, т.к. коэффициент R2 ближе к "1"

#  Задание_2

Создайте модель под названием model с помощью RandomForestRegressor из модуля sklearn.ensemble. Сделайте агрумент n_estimators равным 1000, max_depth должен быть равен 12 и random_state сделайте равным 42. Обучите модель на тренировочных данных аналогично тому, как вы обучали модель LinearRegression, но при этом в метод fit вместо датафрейма y_train поставьте y_train.values[:, 0], чтобы получить из датафрейма одномерный массив Numpy, так как для класса RandomForestRegressor в данном методе для аргумента y предпочтительно применение массивов вместо датафрейма.
Сделайте предсказание на тестовых данных и посчитайте R2. Сравните с результатом из предыдущего задания.
Напишите в комментариях к коду, какая модель в данном случае работает лучше.

In [37]:
from sklearn.ensemble import RandomForestRegressor

In [38]:
model  =  RandomForestRegressor ( max_depth = 12 ,  random_state = 42 ,
                                n_estimators = 1000 ) 

In [39]:
model

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=12,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [40]:
model.fit(X_train, y_train.values[:, 0])

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=12,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [41]:
predict_forest[0:5]

NameError: name 'predict_forest' is not defined

In [ ]:
predict_forest = model.predict(X_test)

In [42]:
check_forest_test = pd.DataFrame({'y_test': y_test['Price'], 
                         'y_pred': predict_forest.flatten()},
                         columns=['y_test', 'y_pred'])

NameError: name 'predict_forest' is not defined

In [43]:
check_forest_test.head()

NameError: name 'check_forest_test' is not defined

Ничего не получилось. НЕ понимаю в чем ошибка... 

In [44]:
print (model.feature_importances_)

[0.03211748 0.00154999 0.0070941  0.0011488  0.01436832 0.40270459
 0.01424477 0.06403265 0.00496762 0.01169177 0.01808961 0.0123114
 0.41567892]


In [45]:
print (model.n_features_)

13


In [46]:
print (model.n_outputs_)

1


In [47]:
print (model.oob_score_)

AttributeError: 'RandomForestRegressor' object has no attribute 'oob_score_'

In [48]:
print (model.oob_prediction_)

AttributeError: 'RandomForestRegressor' object has no attribute 'oob_prediction_'

In [49]:
print(model.predict([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]))

[39.61275]


In [50]:
check_forest_test = pd.DataFrame({'y_test': y_test['Price'], 
                         'y_pred': predict_forest.flatten()},
                         columns=['y_test', 'y_pred'])

NameError: name 'predict_forest' is not defined

# Задание_3

###### Вызовите документацию для класса RandomForestRegressor, найдите информацию об атрибуте feature_importances. 

In [51]:
? RandomForestRegressor

###### С помощью этого атрибута найдите сумму всех показателей важности, установите, какие два признака показывают наибольшую важность.

In [52]:
print (model.feature_importances_)

[0.03211748 0.00154999 0.0070941  0.0011488  0.01436832 0.40270459
 0.01424477 0.06403265 0.00496762 0.01169177 0.01808961 0.0123114
 0.41567892]


In [53]:
print('Cумма всех показателей важности:',sum(model.feature_importances_))

Cумма всех показателей важности: 0.9999999999999993


In [54]:
Признак RM и LSTAT показывают наибольшую важность.

SyntaxError: invalid syntax (<ipython-input-54-ca5a55327f1a>, line 1)

# Задание_4

###### В этом задании мы будем работать с датасетом, с которым мы уже знакомы по домашнему заданию по библиотеке Matplotlib, это датасет Credit Card Fraud Detection. Для этого датасета мы будем решать задачу классификации — определять, какие из транзакциции по кредитной карте являются мошенническими. Данный датасет несбалансирован (так как случаи мошенничества относительно редки), так что применение метрики accuracy не принесет пользы и не поможет выбрать лучшую модель. 

###### Мы будем вычислять AUC, то есть площадь под кривой ROC. Импортируйте из соответствующих модулей RandomForestClassifier, GridSearchCV и train_test_split. Загрузите датасет creditcard.csv и создайте датафрейм df.

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
from sklearn.model_selection import GridSearchCV

In [8]:
from sklearn.model_selection import train_test_split

In [58]:
?train_test_split

In [59]:
df = pd.read_csv('creditcard.csv', sep=',')

###### С помощью метода value_counts с аргументом normalize=True убедитесь в том, что выборка несбалансирована.

In [60]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [61]:
df['Class'].value_counts(normalize=True)

0    0.998273
1    0.001727
Name: Class, dtype: float64

###### Используя метод info, проверьте, все ли столбцы содержат числовые данные и нет ли в них пропусков.

In [62]:
df.info()
# все столбцы содержат числовые данные. Пропусков нет.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
Time      284807 non-null float64
V1        284807 non-null float64
V2        284807 non-null float64
V3        284807 non-null float64
V4        284807 non-null float64
V5        284807 non-null float64
V6        284807 non-null float64
V7        284807 non-null float64
V8        284807 non-null float64
V9        284807 non-null float64
V10       284807 non-null float64
V11       284807 non-null float64
V12       284807 non-null float64
V13       284807 non-null float64
V14       284807 non-null float64
V15       284807 non-null float64
V16       284807 non-null float64
V17       284807 non-null float64
V18       284807 non-null float64
V19       284807 non-null float64
V20       284807 non-null float64
V21       284807 non-null float64
V22       284807 non-null float64
V23       284807 non-null float64
V24       284807 non-null float64
V25       284807 non-null float64
V26  

######  Примените следующую настройку, чтобы можно было просматривать все столбцы датафрейма: pd.options.display.max_columns = 100. Просмотрите первые 10 строк датафрейма df.

In [63]:
pd.options.display.max_columns = 100

In [64]:
df.head(100)

Time        V1        V2        V3        V4        V5        V6  \
0    0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1    0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2    1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3    1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4    2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
5    2.0 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728   
6    4.0  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708   
7    7.0 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118   
8    7.0 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818   
9    9.0 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761   
10  10.0  1.449044 -1.176339  0.913860 -1.375667 -1.971383 -0.629152   
11  10.0  0.384978  0.616109 -0.874300 -0.094019  2.924584  3.317027   
12  10.0  1.249999 -1.221637  0.383930 -1.234899 -1.485419 -0.753230   
13  11.0  1.069374  0.287722  0.828613  2.712520 -0.178398  0.337544   
14  12.0 -2.791855 -0.327771  1.641750  1.767473 -0.136588  0.807596   
15  12.0 -0.752417  0.345485  2.057323 -1.468643 -1.158394 -0.077850   
16  12.0  1.103215 -0.040296  1.267332  1.289091 -0.735997  0.288069   
17  13.0 -0.436905  0.918966  0.924591 -0.727219  0.915679 -0.127867   
18  14.0 -5.401258 -5.450148  1.186305  1.736239  3.049106 -1.763406   
19  15.0  1.492936 -1.029346  0.454795 -1.438026 -1.555434 -0.720961   
20  16.0  0.694885 -1.361819  1.029221  0.834159 -1.191209  1.309109   
21  17.0  0.962496  0.328461 -0.171479  2.109204  1.129566  1.696038   
22  18.0  1.166616  0.502120 -0.067300  2.261569  0.428804  0.089474   
23  18.0  0.247491  0.277666  1.185471 -0.092603 -1.314394 -0.150116   
24  22.0 -1.946525 -0.044901 -0.405570 -1.013057  2.941968  2.955053   
25  22.0 -2.074295 -0.121482  1.322021  0.410008  0.295198 -0.959537   
26  23.0  1.173285  0.353498  0.283905  1.133563 -0.172577 -0.916054   
27  23.0  1.322707 -0.174041  0.434555  0.576038 -0.836758 -0.831083   
28  23.0 -0.414289  0.905437  1.727453  1.473471  0.007443 -0.200331   
29  23.0  1.059387 -0.175319  1.266130  1.186110 -0.786002  0.578435   
..   ...       ...       ...       ...       ...       ...       ...   
70  46.0  1.006589 -0.071105  0.347614  1.329684 -0.193240  0.155418   
71  46.0 -0.378245  0.732925 -0.120154  0.185755  2.594269  3.797183   
72  47.0  1.197839  0.236828  0.509605  0.657659 -0.365488 -0.745101   
73  48.0 -0.580629  0.482684  1.333123 -0.253080 -0.028469 -0.519166   
74  48.0 -1.793406  1.854604  0.979514  1.112262 -0.206403 -0.199546   
75  49.0  1.098608  0.202424  0.525456  1.323436 -0.130486  0.039924   
76  49.0 -0.549626  0.418949  1.729833  0.203065 -0.187012  0.253878   
77  49.0  0.921544 -0.067084  0.077461  0.953638  0.067412  0.016152   
78  50.0 -0.571521  1.071600  1.280110  0.542780  0.574439 -0.259359   
79  50.0 -0.671709  0.594503  0.216416 -0.867311  2.966908  3.632495   
80  51.0  1.259873  0.254240  0.514789  0.620924 -0.475930 -0.992286   
81  52.0  1.147369  0.059035  0.263632  1.211023 -0.044096  0.301067   
82  52.0 -3.005237  2.600138  1.483691 -2.418473  0.306326 -0.824575   
83  53.0 -1.198968 -1.474100  1.840326 -4.515824  0.327567 -0.174469   
84  54.0  1.202398  0.321711  0.281211  0.643689 -0.148669 -0.589739   
85  55.0 -4.575093 -4.429184  3.402585  0.903915  3.002224 -0.491078   
86  55.0 -0.773450  0.853112  0.818254 -0.236070  0.803463 -1.438728   
87  56.0 -0.847998  1.043459  1.267369  1.135529  0.021362  0.336914   
88  56.0  0.086996 -0.051989 -0.497882 -3.151908  2.558400  2.796671   
89  59.0 -0.773293 -4.146007 -0.932038  0.027094 -1.698307  0.460188   
90  59.0  0.921024 -0.162447 -0.094331  0.474084 -0.021486 -0.397506   
91  60.0  1.069141  0.043786  0.309867  1.316694 -0.462394 -0.857888   
92  60.0  1.107029  0.216441  0.538378  1.476398 -0.251942 -0.340680   
93  62.0 -1.035106  0.996013  2.192470 -0.17

###### Создайте датафрейм X из датафрейма df, исключив столбец Class.

In [65]:
X = df.iloc[:,0:-1].copy()
X.tail(3)

Time        V1        V2        V3        V4        V5        V6  \
284804  172788.0  1.919565 -0.301254 -3.249640 -0.557828  2.630515  3.031260   
284805  172788.0 -0.240440  0.530483  0.702510  0.689799 -0.377961  0.623708   
284806  172792.0 -0.533413 -0.189733  0.703337 -0.506271 -0.012546 -0.649617   

              V7        V8        V9       V10       V11       V12       V13  \
284804 -0.296827  0.708417  0.432454 -0.484782  0.411614  0.063119 -0.183699   
284805 -0.686180  0.679145  0.392087 -0.399126 -1.933849 -0.962886 -1.042082   
284806  1.577006 -0.414650  0.486180 -0.915427 -1.040458 -0.031513 -0.188093   

             V14       V15       V16       V17       V18       V19       V20  \
284804 -0.510602  1.329284  0.140716  0.313502  0.395652 -0.577252  0.001396   
284805  0.449624  1.962563 -0.608577  0.509928  1.113981  2.897849  0.127434   
284806 -0.084316  0.041333 -0.302620 -0.660377  0.167430 -0.256117  0.382948   

             V21       V22       V23       V24       V25       V26       V27  \
284804  0.232045  0.578229 -0.037501  0.640134  0.265745 -0.087371  0.004455   
284805  0.265245  0.800049 -0.163298  0.123205 -0.569159  0.546668  0.108821   
284806  0.261057  0.643078  0.376777  0.008797 -0.473649 -0.818267 -0.002415   

             V28  Amount  
284804 -0.026561   67.88  
284805  0.104533   10.00  
284806  0.013649  217.00

###### Создайте объект Series под названием y из столбца Class.

In [66]:
y = df['Class']
type(y)

pandas.core.series.Series

###### Разбейте X и y на тренировочный и тестовый наборы данных при помощи функции train_test_split, используя аргументы: test_size=0.3, random_state=100, stratify=y.  У вас должны получиться объекты X_train, X_test, y_train и y_test.  Просмотрите информацию о их форме.

In [68]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 30 columns):
Time      284807 non-null float64
V1        284807 non-null float64
V2        284807 non-null float64
V3        284807 non-null float64
V4        284807 non-null float64
V5        284807 non-null float64
V6        284807 non-null float64
V7        284807 non-null float64
V8        284807 non-null float64
V9        284807 non-null float64
V10       284807 non-null float64
V11       284807 non-null float64
V12       284807 non-null float64
V13       284807 non-null float64
V14       284807 non-null float64
V15       284807 non-null float64
V16       284807 non-null float64
V17       284807 non-null float64
V18       284807 non-null float64
V19       284807 non-null float64
V20       284807 non-null float64
V21       284807 non-null float64
V22       284807 non-null float64
V23       284807 non-null float64
V24       284807 non-null float64
V25       284807 non-null float64
V26  

In [72]:
y.shape

(284807,)

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100, stratify=y)

In [74]:
X_train.shape

(199364, 30)

In [75]:
y_train.shape

(199364,)

In [76]:
X_test.shape

(85443, 30)

In [77]:
y_test.shape

(85443,)

###### Для поиска по сетке параметров задайте такие параметры: parameters = [{'n_estimators': [10, 15], 'max_features': np.arange(3, 5), 'max_depth': np.arange(4, 7)}]

In [78]:
parameters = [{'n_estimators': [10, 15], 
               'max_features': np.arange(3, 5),
               'max_depth': np.arange(4, 7)}]

###### Создайте модель GridSearchCV со следующими аргументами: estimator=RandomForestClassifier(random_state=100), param_grid=parameters, scoring='roc_auc', cv=3.

In [79]:
Grid = GridSearchCV(estimator=RandomForestClassifier(random_state=100), 
                   param_grid=parameters,
                   scoring='roc_auc',
                   cv=3)

###### Обучите модель на тренировочном наборе данных (может занять несколько минут).

In [80]:
Grid.fit(X_train, y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=100, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid=[{'n_estimators': [10, 15], 'max_features': array([3, 4]), 'max_depth': array([4, 5, 6])}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='roc_auc', verbose=0)

######  Просмотрите параметры лучшей модели с помощью атрибута best_params_.

In [81]:
Grid.best_params_

{'max_depth': 6, 'max_features': 3, 'n_estimators': 15}

###### Предскажите вероятности классов с помощью полученнной модели и метода predict_proba. Из полученного результата (массив Numpy) выберите столбец с индексом 1 (вероятность класса 1) и запишите в массив y_pred_proba.

In [83]:
pp = Grid.predict_proba (X_test)

In [84]:
pp

array([[9.99070828e-01, 9.29171738e-04],
       [9.99704794e-01, 2.95206364e-04],
       [9.99717846e-01, 2.82154033e-04],
       ...,
       [9.99717846e-01, 2.82154033e-04],
       [9.99317795e-01, 6.82204754e-04],
       [9.87539019e-01, 1.24609813e-02]])

In [86]:
pp.shape

(85443, 2)

In [99]:
pp.ndim

2

In [106]:
pp[0:,1]

array([0.00092917, 0.00029521, 0.00028215, ..., 0.00028215, 0.0006822 ,
       0.01246098])

In [108]:
y_pred_proba=pp[0:,1].copy()
y_pred_proba

array([0.00092917, 0.00029521, 0.00028215, ..., 0.00028215, 0.0006822 ,
       0.01246098])

###### Из модуля sklearn.metrics импортируйте метрику roc_auc_score. Вычислите AUC на тестовых данных и сравните с результатом, полученным на тренировочных данных, используя в качестве аргументов массивы y_test и y_pred_proba.

In [9]:
from sklearn.metrics import roc_auc_score

In [110]:
roc_auc_score(y_test, y_pred_proba)

0.9462664156037156

# Дополнительное задание

###### Загрузите датасет Wine из встроенных датасетов sklearn.datasets с помощью функции load_wine в переменную data.Полученный датасет не является датафреймом. Это структура данных, имеющая ключи аналогично словарю. Просмотрите тип данных этой структуры данных и создайте список data_keys, содержащий ее ключи.

In [10]:
from sklearn.datasets import load_wine

In [18]:
wine = load_wine()

In [19]:
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [22]:
data = wine.data

In [30]:
data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [24]:
data.shape

(178, 13)

In [32]:
type(data)

numpy.ndarray

###### Сколько классов содержит целевая переменная датасета? Выведите названия классов.На основе данных датасета (они содержатся в двумерном массиве Numpy) и названий признаков создайте датафрейм под названием X. Выясните размер датафрейма X и установите, имеются ли в нем пропущенные значения.

In [33]:
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [35]:
target = wine.target


In [36]:
type(target)

numpy.ndarray

In [37]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [38]:
target.shape

(178,)

Целевая переменная содержит 3 класса.

In [39]:
numpy.unique(target)

NameError: name 'numpy' is not defined

In [ ]:
for line in boston.DESCR.split('\n'):
    print(line)

###### Добавьте в датафрейм поле с классами вин в виде чисел, имеющих тип данных numpy.int64. Название поля - 'target'.

###### Постройте матрицу корреляций для всех полей X. Дайте полученному датафрейму название X_corr.

###### Создайте список high_corr из признаков, корреляция которых с полем target по абсолютному значению превышает 0.5 (причем, само поле target не должно входить в этот список).

###### Удалите из датафрейма X поле с целевой переменной. Для всех признаков, названия которых содержатся в списке high_corr, вычислите квадрат их значений и добавьте в датафрейм X соответствующие поля с суффиксом '_2', добавленного к первоначальному названию признака. Итоговый датафрейм должен содержать все поля, которые, были в нем изначально, а также поля с признаками из списка high_corr, возведенными в квадрат. Выведите описание полей датафрейма X с помощью метода describe.