# HOMEWORK: 
![alt text][logo]

[logo]: https://avatars.mds.yandex.net/get-banana/60828/x25Dc6RrqSnfveje6clwhi5Vl_banana_20161021_409-220-RUB-1x401x.png/optimize "Logo Title Text"


|**Student**| **Faculty**|
|-------|:------:|
|_Zamolotskii Dmitrii_|_Big DATA_|


### Задание_1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй — числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец — это признак, а строка — наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [148]:
import numpy as np

In [149]:
a = np.array ([[1,2,3,3,1],
              [6,8,11,10,7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [150]:
a = a.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [151]:
a.mean(axis=0)

array([2. , 8.4])

In [152]:
a.mean(axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

In [153]:
mean_a = ([a.mean(axis=0)],[a.mean(axis=1)])
mean_a

([array([2. , 8.4])], [array([3.5, 5. , 7. , 6.5, 4. ])])

### Задание_2

Вычислите массив a_centered, отняв от значений массива а 
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [154]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [155]:
mean_a[0]

[array([2. , 8.4])]

In [156]:
a_centered = a - mean_a[0]
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [157]:
a_centered[0:,:1]

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [158]:
a_centered[0:,1:]

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

### Задание_3

Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [159]:
a_centered_sp = sum(a_centered[0:,:1] * a_centered[0:,1:])
a_centered_sp

array([8.])

In [160]:
N = a.shape[0]

In [161]:
a_centered_sp/(N-1)

array([2.])

### Задание_4

Число, которое мы получили в конце задания 3, является 
ковариацией двух признаков, содержащихся в массиве а.
В задании 3 мы делили сумму произведений центрированных 
признаков на N-1, а не на N, поэтому полученная нами величина 
является несмещенной оценкой ковариации.

Подробнее узнать о ковариации можно [здесь][1]:


В этом задании проверьте получившееся число, вычислив
ковариацию еще одним способом — с помощью функции np.cov.

В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

[1]:[https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html]

In [171]:
?np.cov

In [162]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [168]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [170]:
a_trans = a.T
a.T

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [172]:
np.cov(
    a_trans,
    y=None,
    rowvar=True,
    bias=False,
    ddof=None,
    fweights=None,
    aweights=None,
)

array([[1. , 2. ],
       [2. , 4.3]])

### Задание_5

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price,
в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [22]:
import pandas as pd

In [23]:
authors = pd.DataFrame({'author_id':[1,2,3],
                       'author_name':['Тургенев', 'Чехов', 'Островский']}, 
                       columns=['author_id','author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [24]:
book = pd.DataFrame({'auter_id':[1, 1, 1, 2, 2, 3, 3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price':[450, 300, 350, 500, 450, 370, 290]}, 
                    columns=['auter_id', 'book_title', 'price'])
book

auter_id            book_title  price
0         1           Отцы и дети    450
1         1                 Рудин    300
2         1     Дворянское гнездо    350
3         2      Толстый и тонкий    500
4         2       Дама с собачкой    450
5         3                 Гроза    370
6         3  Таланты и поклонники    290

In [25]:
authors.shape

(3, 2)

In [26]:
book.shape

(7, 3)

In [27]:
authors.columns

Index(['author_id', 'author_name'], dtype='object')

In [28]:
book.columns

Index(['auter_id', 'book_title', 'price'], dtype='object')

In [29]:
book=book.rename(columns = {'auter_id':'author_id'})
book.columns

Index(['author_id', 'book_title', 'price'], dtype='object')

In [30]:
book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
author_id     7 non-null int64
book_title    7 non-null object
price         7 non-null int64
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes


In [31]:
book.info

<bound method DataFrame.info of    author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290>

In [32]:
book.describe

<bound method NDFrame.describe of    author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290>

In [33]:
book.describe()

author_id       price
count   7.000000    7.000000
mean    1.857143  387.142857
std     0.899735   80.976187
min     1.000000  290.000000
25%     1.000000  325.000000
50%     2.000000  370.000000
75%     2.500000  450.000000
max     3.000000  500.000000

### Задание_6

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id

In [55]:
authors_price = pd.merge (authors, book, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание_7

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [35]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [36]:
authors_price ['price']. max()

500

In [132]:
?sort

Object `sort` not found.


In [133]:
?sort_values

Object `sort_values` not found.


In [39]:
authors_price.loc[authors_price ['price']==authors_price ['price'].max()]

author_id author_name        book_title  price
3          2       Чехов  Толстый и тонкий    500

In [40]:
authors_price_1 = authors_price.sort_values(by='price', ascending = [False]) 
authors_price_1

author_id author_name            book_title  price
3          2       Чехов      Толстый и тонкий    500
0          1    Тургенев           Отцы и дети    450
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
2          1    Тургенев     Дворянское гнездо    350
1          1    Тургенев                 Рудин    300
6          3  Островский  Таланты и поклонники    290

In [41]:
top5 = authors_price_1.head()
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [42]:
top5 = top5.reset_index(drop = True)
top5

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

### Задание_8

Создайте датафрейм authors_stat на основе информации из authors_price.
В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора,
минимальная, максимальная и средняя цена на книги этого автора.

In [43]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [106]:
authors_min = authors_price.groupby('author_name')['price'].min()
authors_min

author_name
Островский    290
Тургенев      300
Чехов         450
Name: price, dtype: int64

In [107]:
authors_max = authors_price.groupby('author_name')['price'].max()
authors_max

author_name
Островский    370
Тургенев      450
Чехов         500
Name: price, dtype: int64

In [108]:
authors_mean = authors_price.groupby('author_name')['price'].mean()
authors_mean

author_name
Островский    330.000000
Тургенев      366.666667
Чехов         475.000000
Name: price, dtype: float64

In [109]:
author_stat=pd.concat([autor_min, authors_max, authors_mean], axis =1, sort=False)
author_stat

price  price       price
author_name                          
Островский     290    370  330.000000
Тургенев       300    450  366.666667
Чехов          450    500  475.000000

In [110]:
author_stat.columns = ['min_price', 'max_price', 'mean_price']

In [111]:
author_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

In [112]:
author_stat.reset_index()

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

### Задание_9


 + Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги — твердая или мягкая. В этот столбец поместите данные из следующего списка: ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
 + Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.

 + Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться «твердая» и «мягкая», а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.

 + Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [115]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [116]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [117]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [176]:
?pd.pivot_table

In [177]:
table = pd.pivot_table(authors_price, values='cover', index=['author_name'], aggfunc=np.sum)
table

cover
author_name                     
Островский          мягкаямягкая
Тургенев     твердаямягкаямягкая
Чехов             твердаятвердая

In [181]:
table = pd.pivot_table(authors_price, values='cover', index=['author_name'], 
                       columns=['твердая', 'мягкая'], aggfunc=np.sum, fill_value=0)

#При этом столбцы должны называться «твердая» и «мягкая», а индексами должны быть фамилии авторов.
#Пока не получилось. 
table

ValueError: Grouper for 'cover' not 1-dimensional

In [ ]:
#Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". 
#Затем загрузите из этого файла датафрейм и назовите его book_info2. 
#Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [142]:
book_info = table
book_info.to_pickle('book_info.pkl')

In [144]:
book_info2=pd.read_pickle('book_info.pkl')

In [145]:
book_info==book_info2

cover
author_name book_title                 
Островский  Гроза                  True
            Таланты и поклонники   True
Тургенев    Дворянское гнездо      True
            Отцы и дети            True
            Рудин                  True
Чехов       Дама с собачкой        True
            Толстый и тонкий       True